### PR TITLE
jpn

### PR DESCRIPTION
**Pull request by yyoossk**

### CODE REVIEW

**Comment by J-D-K** [comment]
Thank you. I need to fix a bug quick and I'll update releases for this and the Brazillian Portuguese later.

**Comment by yyoossk** [comment]
thx!

**Comment by J-D-K** [comment]
I have a small favor to ask if you have time. JKSV does not handle languages that don't use spaces like English does well at all. I have added Japanese punctuation to the line breaking rules, but it unfortunately does not fix all the line breaking issues. I'll attach screenshots. If I were to add `\n` as a line breaking sequence, would it be possible to fix this? Sorry, I know nothing about Japanese myself.
2021073019224500-DB1426D1DFD034027CECDE9C2DD914B8

**Comment by yyoossk** [comment]
i will try fix it soon

**Comment by yyoossk** [comment]
fixed!
thx!

**Pull request merged**
