### PR TITLE
Update it.txt

### PR DESCRIPTION
**Pull request by SimoCasa**
Translation in Italian

### CODE REVIEW

**Comment by J-D-K** [comment]
Thanks. I'll check it out soonish.

**Comment by SimoCasa** [comment]
Hope it will help :)

**Comment by J-D-K** [comment]
Sorry it took so long. I'm gonna pull after I merge and generate a newer version with the updated and newer drive strings.

**Comment by SimoCasa** [comment]
Ok👌🏼

**Comment by SimoCasa** [comment]
Hi, I wanted to ask if the French translation file is completed to update the Italian one. If it is, I have already finished the file in Italian (already tested on real hw) :)

**Comment by fennectech** [comment]
You can make a separate PR for it :)

**Pull request merged**
