### PR TITLE
Adding Brazillian Portuguese.

### PR DESCRIPTION
**Pull request by ortega1cba**
This is the Brazillian portuguese language, can be used for Portuguese too, but has some changes between the two.

### CODE REVIEW

**Comment by J-D-K** [comment]
Thanks. I'll check it out when I can. Unfortunately I'm revamping the UI which is going to need more translation work and changes.

**Comment by ortega1cba** [comment]
No problem, I'll translate whatever is necessary.

**Comment by fennectech** [comment]
You can probally get a head start by looking at the lang files in the newui branch

**Comment by J-D-K** [comment]
He actually can't at the moment. A lot of strings I've added need to be made so they are defined and can be read first. Doing that while writing new code holds things up as I've got to jump back and forth.

**Comment by J-D-K** [comment]
So, I'll merge with the master branch so if anyone feels like cloning, they will have your translation. Just keep an eye out for when I merge the newUI branch. If I do that, things are probably either ready or really close to it and strings should be good to go.

**Pull request merged**
