### PR TITLE
Update es-419.txt

### PR DESCRIPTION
**Pull request by impeeza**
Add missing values and correct some minor translation issues for LATAM Spanish.

### CODE REVIEW

**Comment by impeeza** [comment]
Hello there @J-D-K is any bad code or wrong file preventing this file to be merged?  any I can improve or Help.

Thanks a lot for your hard work, regards.

**Comment by J-D-K** [comment]
I haven't actually had a chance to look yet. I actually have some stuff I wrote at work to add some time soon, so it shouldn't be too much longer.

**Comment by impeeza** [comment]
Thanks for answering. Let me know if I can help with anything. Regards

**Comment by impeeza** [comment]
Please do not forget to add this to next version.

regards from Colombia.

**Comment by J-D-K** [comment]
I won't. I'm just way too busy right now to review these and test them.

**Comment by impeeza** [comment]
Don't worry, I don't want to be a pain, Thanks a lot for all your effort and work, regards from Colombia.

**Comment by impeeza** [comment]
@J-D-K Tested the commit df89d8b and this PR works fine.  

But some changes are been added on PR207 final,  better cancel this PR and create a new one using latest version?

**Comment by impeeza** [comment]
Closing this PR to create a new with latest commit

**Pull request closed without merging**
