### PR TITLE
full support for Lang translation in UI

### PR DESCRIPTION
**Pull request by zdm65477730**
- allow trans lang file used in loading page, main page.
- add simplified Chinese support
- add full trans in UI

### CODE REVIEW

**Comment by J-D-K** [comment]
I'll check it out and merge sometime this week, maybe later today. I was gonna do this myself but you saved me a ton of time and headaches.

**Comment by J-D-K** [comment]
I'm not going to merge this as is. It has issues, so in order of what I can see:

The following are error messages that are logged for me and shouldn't be translated as they're not part of the UI:
`infoStatus = 10, "Error committing file to device -> 0x%X\n"`
`infoStatus = 12, "SaveCreate Failed -> "`
`expandSizeFailed = 0, "Extend Failed: %uMB to %uMB  -> %X\n"`

These two do not follow vsprintf format, instead using C++ strings. C++ strings may be safer, but vsprintf allows translators to position titles and variables where needed:
`changeToPopStatus = 0, "changed to"` would be `#%s# changed to #%s#.`
`tmpEmptyPopStatus = 0, "contains illegal or non-ASCII characters."` would be `#%s# contains illegal or non-ASCII characters.`

These I would *prefer* if they were named differently to follow the naming scheme and so they get sorted correctly when exported:
`newSafeTitle` to `swkbdNewSafeTitle`
`expandSize` to `swkbdExpandSize`
`newFolderPopFldMenu` to `folderMenuNew`
`changeToPopStatus` to `popChangeOutputFolder`
`tmpEmptyPopStatus` to `popChangeOutputError`
`newFolderCopyMenu` to `fileModeMenuMkDir`
`settingsMainMenu` to `mainMenuSettings`
`extrasMainMenu` to `mainMenuExtras`

Third is that [initStrings](https://github.com/zdm65477730/JKSV/blob/37e8f10aa89dfcafc58e4c1260c858ec5097e1ee/src/ui/uistr.cpp#L16) is called by default and will probably be called in the future to fill out strings in the event translations aren't fully updated so there aren't empty strings.

That's what I can see right now. I might have more later. Sorry if it seems nit-picky.

**Comment by zdm65477730** [comment]
Hi J-D-K, 

Glad to get comments from you, they are better and I have made a new commit for the changes, thank you.

**Comment by J-D-K** [comment]
OK. I'll have to build it and give a quick test soon. I'll get back to you asap.

**Comment by J-D-K** [comment]
OK. Looks good so far. If I find anything, I'll take care of it myself.

**Pull request merged**
